### ISSUE TITLE
Audio version?

### ISSUE THREAD

**Issue by thomasuster** [maikmerten/node-ogv-seek#1]
Hey, trying to do the same thing with OGG audio. Be able to stream via a seek time, a start time in seconds. What approach / lib would you take if you were me?

Thanks - Tom

**Comment by maikmerten** [comment]
The code works for Ogg audio as well, as the underlying tools (oggz-info and oggz-chop) also work with Ogg Vorbis and Ogg FLAC files. You may want to serve the data as "audio/ogg" (instead of "video/ogg"), though.

edit: Note that .ogg, .oga and .ogv files are all the same format - plain good old Ogg.
